### ISSUE TITLE
Feature: New statement "log" to print and log message to syslog

### ISSUE THREAD

**Issue by trinnguyen** [trinnguyen/bahndsl#3]
## Frontend
- Add new expression for logging in the syntax definition for interlocking behaviour:
```
log(object)
```

- An object could be: `string` or `number` or `bool` or `float`

- Example:

```ruby
def request_route(string src_signal_id, string dst_signal_id, string train_id): string
  # log literal (type string)
  log("start request_route")
  # log variable (type int)
  log(src_signal_id)
  string route_ids[] = get routes from src_signal_id to dst_signal_id
  # log variable (type bool)
  log(route_ids.len > 0)

  # log signal state (type string)
  string src_state = get state src_signal_id
  log(src_state)
end
```

## Backend
- In generated SCCharts model, generate C function calls to below new methods
- Create custom C functions, example prototypes in bahn_data_util.code:
```
void log_int(int value);
void log_string(const char *value);
void log_bool(bool value);
```
- Implement these functions in `swtbahn-cli` by calling `syslog`

**Comment by trinnguyen** [comment]
@eyip002 I put here the design of a new statement for logging directly from BahnDSL

**Comment by eyip002** [comment]
> ```ruby
>   # log variable (type bool)
>   log(route_ids.len)
> ```
Should this example be something like `log(route_ids.len > 0)` instead?

**Comment by trinnguyen** [comment]
Yes, it should be like that. I will update the example

**Comment by eyip002** [comment]
1. Extend [grammar](https://github.com/trinnguyen/bahndsl/blob/d9bb3befa483807b7716415a5cb024ed2914c501/src/de.uniba.swt.dsl/src/de/uniba/swt/dsl/Bahn.xtext#L419) with `BehaviourLogExpr`:

```
BehaviourLogExpr returns BehaviourExpr:
	{BehaviourLogExpr}
	'log' logExpr= PrimaryExpr
;
```

2. Normalise `BehaviourLogExpr` in [SyntacticTransformer.java](https://github.com/trinnguyen/bahndsl/blob/d9bb3befa483807b7716415a5cb024ed2914c501/src/de.uniba.swt.dsl/src/de/uniba/swt/dsl/normalization/SyntacticTransformer.java#L108)

3. Update [bahn_data_util.code](https://github.com/trinnguyen/bahndsl/blob/master/src/de.uniba.swt.dsl/resources/bahn_data_util.code) with
```c
#include <stdio.h>

void log_int(int value);
void log_float(float value);
void log_string(const char *value);
void log_bool(bool value);
```

4. Update [bahn_data_util_source.code](https://github.com/trinnguyen/bahndsl/blob/master/src/de.uniba.swt.dsl/resources/bahn_data_util_source.code) with 
```c
void log_int(int value) {}
void log_float(float value) {}
void log_string(const char *value) {}
void log_bool(bool value) {}
```
