### ISSUE TITLE
Add orientation to route

### ISSUE THREAD

**Issue by trinnguyen** [trinnguyen/bahndsl#4]
- [x] Add orientation to route (in YAML file): `anticlockwise` for down -> up, `clockwise` for up -> down
- [ ] Validation: Make sure all blocks in the same route has the same direction (all are down->up or all are up->down). What happen if some blocks have different directions (valid route)?

**Comment by trinnguyen** [comment]
The orientation is added in:
- https://github.com/trinnguyen/bahndsl/commit/ef8efb6844f31788e8d9082684110e07edacefdc
- https://github.com/trinnguyen/bahndsl/commit/c690ee0d6746697e6305205428fdc92e7b5ccf50

**Comment by eyip002** [comment]
> * [x]  Add orientation to route (in YAML file): `anticlockwise` for down -> up, `clockwise` for up -> down
> * [ ]  Validation: Make sure all blocks in the same route has the same direction (all are down->up or all are up->down). What happen if some blocks have different directions (valid route)?

Is the validation needed? I thought that a valid route required all blocks/points/crossings to be in the same direction?

**Comment by eyip002** [comment]
- More reliable to use the block orientation that the source signal is attached to: the train always needs to exit the block by going past the source signal
- Blocks that are connected in reverse to the railway layout convention have to be marked explicitly in the configuration file with "reversed"
- The Kehrschleifenmodul actively reverses the block's orientation, but the reversal is dependent on whether train exits the block from where it entered. There is no reliable method to correctly infer the train's orientation when it stops in the reversing loop

**Comment by eyip002** [comment]
Tested on the SWTbahn Standard platform and automatic driving works, except for stopping within the reversing loop.

**Comment by trinnguyen** [comment]
> Is the validation needed? I thought that a valid route required all blocks/points/crossings to be in the same direction?

So far, a valid route does not care whether all blocks are in the same orientations or not (it is fine that some blocks can be down->up, others can be up->down). We had concept of one-way traffic for block which restricts the route to use that block for a specific direction only. However, it is not related to the orientation.

Now with orientation, we should only accept route with consistent orientation across block members. For example: in one route, all blocks must be down->up, or some blocks might be up->down and having `reversed` enabled.

**Comment by trinnguyen** [comment]
Shouldn't add validation, because one block can be visitted multiple times in in different orientations.
