### ISSUE TITLE
Unable to reference arrays declared inside a for-loop

### ISSUE THREAD

**Issue by eyip002** [trinnguyen/bahndsl#40]
For the `get config`s that return an array, when they are used inside a for-loop, the compiler is unable to resolve the LHS variable. The problem does not occur with while-loops.

```
def funcA()
    string foo[] = {""}
    string bar2[] = {""}
    for string id in foo
    
        # Compiles fine
        string bar1 = get config block.id id

        # Compiles fine
        bar2 = get config block.overlaps id
        
        # Compilation error: cannot resolve LHS variable (bar2)
        string bar3[] = get config block.overlaps id
 
   end
end
```

**Comment by eyip002** [comment]
Seems like nested `ForeachStmt`s are not normalised into `IterationStmt` statements.

https://github.com/trinnguyen/bahndsl/blob/fb2500ac9eb724b1df20a6e981bfd370f6c9d7d9/src/de.uniba.swt.dsl/src/de/uniba/swt/dsl/normalization/ForeachNormalizer.java#L74-L80

**Comment by eyip002** [comment]
Work-around is to manually rewrite nested for-loops into while-loops

**Comment by trinnguyen** [comment]
The root cause of this is about the array variable decl inside the loop. The array normaliser did not process the statement list of `ForeachStmts` probably:

```
string bar3[] = get config block.overlaps id
```

https://github.com/trinnguyen/bahndsl/blob/master/src/de.uniba.swt.dsl/src/de/uniba/swt/dsl/normalization/ArrayNormalizer.java#L91-L93

A quick solution is to adding normalisation for the for-each content:
```java
if (stmt instanceof ForeachStmt) {
  normalizeStmtList(((ForeachStmt) stmt).getStmts());
  return generateArrayVarIfNeeded(((ForeachStmt) stmt).getArrayExpr());
}
```

**Comment by eyip002** [comment]
Issue still remains for nested for-loops:

```
def test(int items[])
    int foo[] = { 1 }
    for int id1 in foo
        for int id in foo 
           # Empty
        end
    end
end
```
