### ISSUE TITLE
Proposal: Deprecate VS Code Support

### ISSUE THREAD

**Issue by eyip002** [trinnguyen/bahndsl#45]
Maintaining VS Code support is becoming more and more difficult because of lack of developer expertise and language server issues. The proposal is to only focus development on the command line app and Eclipse IDE.

VS Code only supports the following features:
- Syntax highlighting
- Code completion, refactoring, formatting using LSP
- Automated generation of YAML configuration files and SCCharts files
- Bugs:
  -  #9
  - https://github.com/trinnguyen/bahndsl/issues/44#issuecomment-1444197500
- Unresolved issues:
  -  #7 

The Eclipse IDE supports the following **additional** features:
- Custom outline of Bahn configuration files
- Language support for SCCharts
- Automated compilation of SCCharts files into C files or shared libraries

**Comment by eyip002** [comment]
- [ ] Update [Readme](https://github.com/trinnguyen/bahndsl/blob/master/README.md): 
  - [ ] Mention that VS Code support is deprecated
  - [ ] Remove badge to VS Code marketplace 
- [ ] Update [Readme](https://github.com/trinnguyen/bahndsl/blob/master/src/vscode-bahn/README.md)
  - [ ] Mention that VS Code support is deprecated

**Comment by trinnguyen** [comment]
I support this proposal to phase out the VSCode extension. It has always required certain effort to make things smooth following backend changes. Its benefits are more about providing a quick and fast code editor compared to Eclipse-based BahnIDE. But anyway, the IDE has all of its functionalities plus advanced features. 
Let me know when you finish removing it, I will delete the VSCode extension on marketplace.

**Comment by eyip002** [comment]
@trinnguyen I have now removed the VS Code extension from the project.

**Comment by trinnguyen** [comment]
@eyip002 Thanks. I have removed the VSCode extension from Marketplace to avoid confusion.
