### ISSUE TITLE
Upgrade to Kieler 1.2.0

### ISSUE THREAD

**Issue by trinnguyen** [trinnguyen/bahndsl#8]

**Comment by eyip002** [comment]
http://rtsys.informatik.uni-kiel.de/~kieler/files/release_sccharts_1.2.0/cli/

**Comment by trinnguyen** [comment]
Note: KIELER based on VSCode https://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/KEITH

**Comment by eyip002** [comment]
Updated *.target file (0e0a333cb577d6f706ce644a1f1b9ea00f5d49ea) and plugins (5125ae4c07a22daa6a669a032f0e516a4e5ee5d4)

Updated *.product to activate KIELER plugins for SCCharts editor and diagram support (490391ae12f0d9814fb5f45d14057dfa13a8c3c5).
