### ISSUE TITLE
VSCode extension does not properly compute the expected parameters of standardlib methods

### ISSUE THREAD

**Issue by eyip002** [trinnguyen/bahndsl#9]
Consider the method with signature `def get_shortest_route(string route_ids[]): string` that has been defined in `standardlib.bahn`. Every time the standardlib methods are normalised, the expected number of arguments increases.

### VSCode reports an extra argument is required (of type int)
<img width="837" alt="Screen Shot 2021-07-20 at 12 33 28" src="https://user-images.githubusercontent.com/7035180/126315330-2dd2b4ae-9bfb-43ec-a471-1c1b2de3485e.png">
<img width="413" alt="Screen Shot 2021-07-20 at 12 35 15" src="https://user-images.githubusercontent.com/7035180/126315336-c4584247-e236-451d-8834-0ebe17fd9163.png">

### Bahn IDE correctly computes the expected arguments:
<img width="590" alt="Screen Shot 2021-07-20 at 12 35 48" src="https://user-images.githubusercontent.com/7035180/126315337-a23bbcec-2ebe-4fc8-9f97-681e723de91f.png">

**Comment by trinnguyen** [comment]
This issue might be caused by the Array Normalizer: https://github.com/trinnguyen/bahndsl/blob/master/src/de.uniba.swt.dsl/src/de/uniba/swt/dsl/normalization/ArrayNormalizer.java
